-- Semilla de «Contabilidad Básica».
--
-- Generado desde src/data/{aprende,ejercicios,planCuentas}.js, que hasta
-- esta migración eran la fuente. El contenido es idéntico: mismas 12
-- láminas, mismas 22 cuentas, mismos 18 ejercicios con sus montos y notas.

insert into public.clases (slug, nombre, etiqueta, titular, bajada, orden) values (
  'contabilidad-basica',
  'Contabilidad Básica',
  'Práctica de partida doble',
  'Arma el asiento, línea por línea.',
  '18 hechos económicos, de básico a avanzado. Lees el hecho, eliges las cuentas, decides el lado y verificas. La retroalimentación te dice qué está mal sin darte la respuesta.'
, 1);

with c as (select id from public.clases where slug = 'contabilidad-basica')
insert into public.laminas (clase_id, orden, etiqueta, titulo, cuerpo, visual, datos, imagen)
select c.id, v.* from c, (values
  (1, 'Contabilidad for dummies', '[{"t":"Contabilidad "},{"t":"1:1","acento":true}]'::jsonb, '[{"tipo":"p","texto":"De la ecuación contable a las cuentas T, en 12 pasos."}]'::jsonb, null::text, '{}'::jsonb, '{"src":"/aprende/01-patrick.webp","alt":"Patrick y Bob Esponja sentados en la arena frente a un juego de mesa con billetes y una caja registradora."}'::jsonb),
  (2, 'El problema', '[{"t":"Entrada "},{"t":"Simple","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Durante siglos los comerciantes llevaron entradas y salidas de dinero en una sola columna. Si la caja sube 1.000, ese libro no distingue entre tres hechos completamente distintos:"},{"tipo":"lista","items":["Lo gané vendiendo","Me lo prestaron","Vendí una máquina"]},{"tipo":"p","texto":"Tres realidades opuestas, el mismo registro."}]'::jsonb, 'registro', '{"titulo":"Caja · libro de una columna","filas":[{"signo":"+","monto":"1.000","marca":"¿?"},{"signo":"−","monto":"350"},{"signo":"+","monto":"1.000","marca":"¿?"},{"signo":"−","monto":"120"},{"signo":"+","monto":"1.000","marca":"¿?"}],"pie":{"rotulo":"Saldo","valor":"2.530"}}'::jsonb, null::jsonb),
  (3, 'Fundamento', '[{"t":"Activos","acento":true},{"t":" = Pasivos + Patrimonio"}]'::jsonb, '[{"tipo":"p","texto":"Todo lo que un negocio posee fue financiado de una de dos formas: con plata de terceros, o con plata de los dueños. No hay una tercera opción. Por eso la ecuación siempre cuadra."}]'::jsonb, null::text, '{}'::jsonb, '{"src":"/aprende/03-krusty.jpg","alt":"El Crustáceo Cascarudo de noche, iluminado, con su letrero en forma de concha al lado."}'::jsonb),
  (4, 'Fundamento', '[{"t":"Patrimonio","acento":true},{"t":" = Activos − Pasivos"}]'::jsonb, '[{"tipo":"p","texto":"Lo que realmente es mío es todo lo que tengo, menos todo lo que debo."}]'::jsonb, null::text, '{}'::jsonb, '{"src":"/aprende/04-patrimonio.jpg","alt":"Don Cangrejo abrazando y oliendo un fajo de billetes con cara de felicidad.","encuadre":"contener"}'::jsonb),
  (5, 'Fundamento', '[{"t":"Pasivos","acento":true},{"t":" = Activos − Patrimonio"}]'::jsonb, '[{"tipo":"p","texto":"Los pasivos son la parte de tus activos que no es realmente tuya. Tú eres el poseedor, pero otro es el dueño."}]'::jsonb, null::text, '{}'::jsonb, '{"src":"/aprende/05-caja.webp","alt":"Inauguración del Banco de Fondo de Bikini: una fila de peces espera frente a la cinta roja."}'::jsonb),
  (6, 'Historia · Siglo XV', '[{"t":"El método "},{"t":"veneciano","acento":true}]'::jsonb, '[{"tipo":"p","texto":"En la Venecia del Renacimiento, el comercio marítimo movía capital de decenas de socios, en varias monedas, a través de rutas de meses. La partida simple no aguantaba esa complejidad."},{"tipo":"p","texto":"Los mercaderes italianos llevaban ya cerca de dos siglos desarrollando una alternativa: registrar dos veces cada transacción."}]'::jsonb, null::text, '{}'::jsonb, '{"src":"/aprende/06-venecia.jpg","alt":"Pintura de Canaletto del Bacino de San Marcos en Venecia, lleno de góndolas frente al Palacio Ducal."}'::jsonb),
  (7, 'Historia · 1494', '[{"t":"Un fraile lo puso "},{"t":"por escrito","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Luca Pacioli, matemático, publicó en Venecia la Summa de Arithmetica. No inventó la partida doble: documentó lo que los mercaderes ya hacían — y al imprimirlo, lo volvió estándar en toda Europa."},{"tipo":"p","texto":"Es la razón por la que hoy, 500 años después, seguimos usando el mismo sistema."}]'::jsonb, null::text, '{}'::jsonb, '{"src":"/aprende/07-pacioli.jpg","alt":"Retrato de Luca Pacioli con hábito de fraile, señalando una figura geométrica sobre una pizarra junto a un libro abierto.","encuadre":"contener"}'::jsonb),
  (8, 'Partida doble', '[{"t":"Todo hecho económico cambia "},{"t":"dos cosas","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Nunca entra dinero solo. Entra dinero y nace una obligación. O entra dinero y se genera un ingreso. La partida doble registra la causa y el efecto como dos anotaciones simultáneas, en lados opuestos y por el mismo monto."},{"tipo":"p","texto":"Ahí está la respuesta que la partida simple no podía dar: no solo cuánto se movió, sino por qué."}]'::jsonb, 'flujo', '{"nodos":[{"texto":"Causa"},{"texto":"Efecto"}],"imagenEnMedio":true}'::jsonb, '{"src":"/aprende/08-causa.jpg","alt":"Bob Esponja en versión realista y desgastada, fumando un cigarrillo con cara de cansancio."}'::jsonb),
  (9, 'Partida doble', '[{"t":"Un sistema que "},{"t":"se verifica solo","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Si cada transacción registra débitos iguales a créditos, entonces en todo el libro los débitos totales deben igualar a los créditos totales. Siempre. Sin excepción."},{"tipo":"p","texto":"Cuando no cuadra, hay un error."}]'::jsonb, 'balance', '{"columnas":[{"rotulo":"Débitos","filas":[{"cuenta":"Caja","monto":"1.200.000"},{"cuenta":"Inventario","monto":"450.000"},{"cuenta":"Gasto arriendo","monto":"350.000"}],"total":"2.000.000"},{"rotulo":"Créditos","filas":[{"cuenta":"Obligación bancaria","monto":"1.000.000"},{"cuenta":"Ingreso por ventas","monto":"800.000"},{"cuenta":"Proveedores","monto":"200.000"}],"total":"2.000.000"}],"signo":"=","sello":"Los totales coinciden"}'::jsonb, null::jsonb),
  (10, 'Concepto clave', '[{"t":"Débito y crédito son solo una "},{"t":"posición","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Débito no significa bueno. Crédito no significa malo. No significan nada por sí solos. Débito es la anotación de la izquierda. Crédito es la de la derecha."},{"tipo":"p","texto":"Vienen del latín debere y credere, y de ahí salen esos términos: deudores a la izquierda, acreedores a la derecha. Lo que un débito hace depende únicamente de qué tipo de cuenta esté tocando."}]'::jsonb, 'partido', '{"mitades":[{"rotulo":"Débito"},{"rotulo":"Crédito"}],"reglas":true}'::jsonb, null::jsonb),
  (11, 'Concepto clave', '[{"t":"Cinco familias, "},{"t":"dos lados","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Cada cuenta pertenece a una de cinco familias, y cada familia vive de un lado:"},{"tipo":"fichas","leyenda":"aumentan al","items":[{"texto":"Activos","ficha":"Débito","tono":"info","flecha":"arriba"},{"texto":"Gastos","ficha":"Débito","tono":"info","flecha":"arriba"},{"texto":"Pasivos","ficha":"Crédito","tono":"ciruela","flecha":"arriba"},{"texto":"Patrimonio","ficha":"Crédito","tono":"ciruela","flecha":"arriba"},{"texto":"Ingresos","ficha":"Crédito","tono":"ciruela","flecha":"arriba"}]},{"tipo":"p","texto":"No hay que memorizarlo: sale de la ecuación. Los activos están a la izquierda, así que crecen por la izquierda."}]'::jsonb, 'tabla', '{"columnas":[{"rotulo":"Familia"},{"rotulo":"Aumenta","sentido":"arriba"},{"rotulo":"Disminuye","sentido":"abajo"}],"filas":[{"celdas":[{"texto":"Activos"},{"texto":"Débito","tono":"info","flecha":"izquierda"},{"texto":"Crédito","tono":"ciruela","flecha":"derecha"}]},{"celdas":[{"texto":"Gastos"},{"texto":"Débito","tono":"info","flecha":"izquierda"},{"texto":"Crédito","tono":"ciruela","flecha":"derecha"}]},{"celdas":[{"texto":"Pasivos"},{"texto":"Crédito","tono":"ciruela","flecha":"derecha"},{"texto":"Débito","tono":"info","flecha":"izquierda"}]},{"celdas":[{"texto":"Patrimonio"},{"texto":"Crédito","tono":"ciruela","flecha":"derecha"},{"texto":"Débito","tono":"info","flecha":"izquierda"}]},{"celdas":[{"texto":"Ingresos"},{"texto":"Crédito","tono":"ciruela","flecha":"derecha"},{"texto":"Débito","tono":"info","flecha":"izquierda"}]}]}'::jsonb, null::jsonb),
  (12, 'Cuentas T', '[{"t":"La "},{"t":"herramienta","acento":true},{"t":" de trabajo"}]'::jsonb, '[{"tipo":"p","texto":"Una cuenta T es una sola cuenta dibujada como su libro mayor: nombre arriba, débitos a la izquierda, créditos a la derecha, saldo abajo del lado que corresponda."},{"tipo":"p","texto":"Es el borrador con el que piensa un contador antes de escribir un asiento."}]'::jsonb, 'bloqueT', '{"nombre":"Nombre de la cuenta","lados":[{"rotulo":"Débito"},{"rotulo":"Crédito"}],"pie":"Saldo"}'::jsonb, null::jsonb)
) as v(orden, etiqueta, titulo, cuerpo, visual, datos, imagen);

with c as (select id from public.clases where slug = 'contabilidad-basica')
insert into public.cuentas (clase_id, nombre, padre, contraria, razon)
select c.id, v.* from c, (values
  ('Caja', 'Activo', false, 'es dinero que el negocio ya controla'),
  ('Bancos', 'Activo', false, 'es dinero del negocio depositado en una entidad financiera'),
  ('Cuentas por Cobrar', 'Activo', false, 'es un derecho de cobro a favor del negocio'),
  ('Inventario', 'Activo', false, 'es mercancía que el negocio posee para vender'),
  ('Seguros Pagados por Anticipado', 'Activo', false, 'es un derecho a cobertura futura ya pagada'),
  ('Equipo', 'Activo', false, 'es un bien que el negocio usa durante varios períodos'),
  ('Vehículos', 'Activo', false, 'es un bien que el negocio usa durante varios períodos'),
  ('Depreciación Acumulada', 'Activo', true, 'vive dentro del Activo aunque lo reste: acumula el desgaste del bien'),
  ('Cuentas por Pagar', 'Pasivo', false, 'es una deuda con un proveedor'),
  ('Obligaciones Financieras', 'Pasivo', false, 'es una deuda con una entidad financiera'),
  ('Ingresos Diferidos', 'Pasivo', false, 'es dinero ya cobrado por algo que todavía debes entregar'),
  ('IVA por Pagar', 'Pasivo', false, 'es dinero recaudado que le pertenece al Estado'),
  ('Salarios por Pagar', 'Pasivo', false, 'es una deuda con los empleados por trabajo ya recibido'),
  ('Capital Social', 'Patrimonio', false, 'es lo que el dueño aportó al negocio'),
  ('Retiros del Propietario', 'Patrimonio', true, 'vive dentro del Patrimonio aunque lo reste: registra lo que el dueño sacó'),
  ('Ingresos por Ventas', 'Ingreso', false, 'registra lo que el negocio ganó al entregar producto o servicio'),
  ('Costo de Ventas', 'Gasto', false, 'es el costo del producto ya entregado, consumido en el período'),
  ('Gasto de Arriendo', 'Gasto', false, 'es un beneficio ya consumido en el período'),
  ('Gasto de Salarios', 'Gasto', false, 'es trabajo ya recibido y consumido en el período'),
  ('Gasto de Seguros', 'Gasto', false, 'es la porción de cobertura que ya se consumió'),
  ('Gasto de Servicios Públicos', 'Gasto', false, 'es un consumo del período'),
  ('Gasto de Depreciación', 'Gasto', false, 'es el desgaste del período llevado al resultado')
) as v(nombre, padre, contraria, razon);

with c as (select id from public.clases where slug = 'contabilidad-basica')
insert into public.preguntas (clase_id, codigo, orden, tipo, nivel, enunciado, aviso, nota, datos)
select c.id, v.* from c, (values
  ('01', 1, 'asiento', 'Básico', 'Doña Ruca abre su panadería y aporta 5.000.000 de su bolsillo, que deposita en la caja del negocio.', null::text, 'El dinero entra al negocio (activo sube, débito) y el propietario adquiere un derecho sobre él (patrimonio sube, crédito). El negocio y la persona son entidades distintas: por eso el aporte crea una obligación conceptual del negocio hacia su dueño.', '{"lineas":[{"cuenta":"Caja","padre":"Activo","lado":"Débito","monto":5000000},{"cuenta":"Capital Social","padre":"Patrimonio","lado":"Crédito","monto":5000000}]}'::jsonb),
  ('02', 2, 'asiento', 'Básico', 'Compra un horno industrial por 2.000.000, pagando de contado.', null::text, 'Cambias un activo por otro. El patrimonio no se mueve: la panadería no es más rica ni más pobre, solo tiene el valor en otra forma. Comprar equipo nunca es un gasto en el momento de la compra.', '{"lineas":[{"cuenta":"Equipo","padre":"Activo","lado":"Débito","monto":2000000},{"cuenta":"Caja","padre":"Activo","lado":"Crédito","monto":2000000}]}'::jsonb),
  ('03', 3, 'asiento', 'Básico', 'Compra harina e insumos por 800.000 a un proveedor, que le da 30 días para pagar.', null::text, 'No se movió un peso de caja y aun así hay un hecho económico que registrar. Entra mercancía (activo) y nace una deuda (pasivo). Este es el caso que un sistema de solo-efectivo no puede ver.', '{"lineas":[{"cuenta":"Inventario","padre":"Activo","lado":"Débito","monto":800000},{"cuenta":"Cuentas por Pagar","padre":"Pasivo","lado":"Crédito","monto":800000}]}'::jsonb),
  ('04', 4, 'asiento', 'Básico', 'Vende pan de contado por 300.000.', null::text, 'Caja es Activo, Ingresos por Ventas es Ingreso. Son cuentas padre distintas aunque se muevan juntas: una es lo que tienes, la otra es el registro de que lo ganaste.', '{"lineas":[{"cuenta":"Caja","padre":"Activo","lado":"Débito","monto":300000},{"cuenta":"Ingresos por Ventas","padre":"Ingreso","lado":"Crédito","monto":300000}]}'::jsonb),
  ('05', 5, 'asiento', 'Básico', 'Le abona 500.000 en efectivo al proveedor de harina.', null::text, 'Pagar una deuda no es un gasto: el gasto se registró cuando recibiste el beneficio; aquí solo bajan un activo y un pasivo al mismo tiempo.', '{"lineas":[{"cuenta":"Cuentas por Pagar","padre":"Pasivo","lado":"Débito","monto":500000},{"cuenta":"Caja","padre":"Activo","lado":"Crédito","monto":500000}],"reconstruido":true}'::jsonb),
  ('06', 6, 'asiento', 'Básico', 'Paga 200.000 en efectivo por el arriendo del local del mes que acaba de terminar.', null::text, 'El mes ya pasó: el beneficio se consumió, entonces sí es gasto. Los gastos son débito porque reducen el patrimonio, y el patrimonio baja por el lado del débito.', '{"lineas":[{"cuenta":"Gasto de Arriendo","padre":"Gasto","lado":"Débito","monto":200000},{"cuenta":"Caja","padre":"Activo","lado":"Crédito","monto":200000}]}'::jsonb),
  ('07', 7, 'asiento', 'Intermedio', 'Le vende pan a un colegio por 600.000 a crédito. El colegio pagará en 30 días.', null::text, 'El ingreso se reconoce cuando entregas el pan, no cuando te pagan. No entró efectivo y sin embargo hay ingreso: si tu sistema equipara "entró plata" con "hubo venta", aquí se rompe.', '{"lineas":[{"cuenta":"Cuentas por Cobrar","padre":"Activo","lado":"Débito","monto":600000},{"cuenta":"Ingresos por Ventas","padre":"Ingreso","lado":"Crédito","monto":600000}]}'::jsonb),
  ('08', 8, 'asiento', 'Intermedio', 'Recibe un préstamo bancario de 3.000.000, desembolsado directamente a la cuenta del negocio.', null::text, 'Entró dinero pero no es ingreso: es deuda. Distinguir "plata prestada" de "plata ganada" es justamente lo que la partida simple no podía hacer.', '{"lineas":[{"cuenta":"Bancos","padre":"Activo","lado":"Débito","monto":3000000},{"cuenta":"Obligaciones Financieras","padre":"Pasivo","lado":"Crédito","monto":3000000}]}'::jsonb),
  ('09', 9, 'asiento', 'Intermedio', 'Paga 1.200.000 en efectivo por la póliza de seguro del local, que cubre los próximos 6 meses.', null::text, 'Todavía no se consume nada: tienes el derecho a 6 meses de cobertura futura, y un derecho es un activo. Es el espejo exacto de los ingresos diferidos, pero del lado izquierdo del balance.', '{"lineas":[{"cuenta":"Seguros Pagados por Anticipado","padre":"Activo","lado":"Débito","monto":1200000},{"cuenta":"Caja","padre":"Activo","lado":"Crédito","monto":1200000}]}'::jsonb),
  ('10', 10, 'asiento', 'Intermedio', 'Al cierre del mes, registra el consumo de un mes de esa póliza de seguro.', null::text, 'Este es un asiento de ajuste: no lo dispara una transacción, lo dispara el paso del tiempo. 1.200.000 ÷ 6 = 200.000. El activo se va convirtiendo en gasto a medida que se consume.', '{"lineas":[{"cuenta":"Gasto de Seguros","padre":"Gasto","lado":"Débito","monto":200000},{"cuenta":"Seguros Pagados por Anticipado","padre":"Activo","lado":"Crédito","monto":200000}]}'::jsonb),
  ('11', 11, 'asiento', 'Intermedio', 'El colegio paga los 600.000 que debía, en efectivo.', null::text, 'Aquí NO hay ingreso. El ingreso ya se registró en el ejercicio 07. Volver a registrarlo duplicaría las ventas del mes. Solo cambia la forma del activo: de derecho de cobro a efectivo.', '{"lineas":[{"cuenta":"Caja","padre":"Activo","lado":"Débito","monto":600000},{"cuenta":"Cuentas por Cobrar","padre":"Activo","lado":"Crédito","monto":600000}]}'::jsonb),
  ('12', 12, 'asiento', 'Intermedio', 'Paga 900.000 en efectivo de salarios a sus empleados por el mes trabajado.', null::text, 'El trabajo ya se recibió y se consumió, entonces es gasto del período.', '{"lineas":[{"cuenta":"Gasto de Salarios","padre":"Gasto","lado":"Débito","monto":900000},{"cuenta":"Caja","padre":"Activo","lado":"Crédito","monto":900000}]}'::jsonb),
  ('13', 13, 'asiento', 'Intermedio', 'Doña Ruca retira 150.000 en efectivo del negocio para un gasto personal.', null::text, 'Retiros del Propietario es Patrimonio, pero es una cuenta contraria: reduce el patrimonio, por eso se mueve al débito. Se lleva aparte del Capital Social para poder ver por separado cuánto metió el dueño y cuánto sacó.', '{"lineas":[{"cuenta":"Retiros del Propietario","padre":"Patrimonio","lado":"Débito","monto":150000},{"cuenta":"Caja","padre":"Activo","lado":"Crédito","monto":150000}]}'::jsonb),
  ('14', 14, 'asiento', 'Avanzado', 'Registra el costo de la mercancía vendida durante el mes: el pan que salió del inventario le costó a la panadería 480.000 producirlo.', null::text, 'Este asiento va aparte del de la venta y por un monto distinto: aquí va el costo, allá iba el precio. La diferencia entre ambos es tu margen bruto. Mezclarlos corrompe el inventario y el margen a la vez.', '{"lineas":[{"cuenta":"Costo de Ventas","padre":"Gasto","lado":"Débito","monto":480000},{"cuenta":"Inventario","padre":"Activo","lado":"Crédito","monto":480000}]}'::jsonb),
  ('15', 15, 'asiento', 'Avanzado', 'Un cliente le paga a la empresa 1.200.000 de contado por una suscripción anual que aún no se ha prestado.', null::text, 'Cobraste pero no ganaste todavía: le debes al cliente 12 meses de servicio, y eso es un pasivo real. Reconocer esto como ingreso el día del cobro es el error más común en software de suscripción.', '{"lineas":[{"cuenta":"Caja","padre":"Activo","lado":"Débito","monto":1200000},{"cuenta":"Ingresos Diferidos","padre":"Pasivo","lado":"Crédito","monto":1200000}]}'::jsonb),
  ('16', 16, 'asiento', 'Avanzado', 'Pasa un mes y la empresa reconoce la porción de esa suscripción que ya prestó.', null::text, '1.200.000 ÷ 12 = 100.000. El pasivo se extingue a medida que cumples la obligación, y ahí sí nace el ingreso. Ningún peso de caja se mueve en este asiento.', '{"lineas":[{"cuenta":"Ingresos Diferidos","padre":"Pasivo","lado":"Débito","monto":100000},{"cuenta":"Ingresos por Ventas","padre":"Ingreso","lado":"Crédito","monto":100000}]}'::jsonb),
  ('17', 17, 'asiento', 'Avanzado', 'La panadería vende 1.000.000 en producto de contado, más IVA del 19% que debe recaudar y entregar a la DIAN.', 'Tres líneas.', 'El IVA nunca fue tuyo: lo recaudas como agente de retención y lo debes, por eso es pasivo. Si registras 1.190.000 como ingreso, inflas las ventas y subestimas la deuda tributaria.', '{"lineas":[{"cuenta":"Caja","padre":"Activo","lado":"Débito","monto":1190000},{"cuenta":"Ingresos por Ventas","padre":"Ingreso","lado":"Crédito","monto":1000000},{"cuenta":"IVA por Pagar","padre":"Pasivo","lado":"Crédito","monto":190000}]}'::jsonb),
  ('18', 18, 'asiento', 'Avanzado', 'Al cierre del mes registra la depreciación del horno: 100.000 correspondientes al desgaste del período.', null::text, 'Depreciación Acumulada es Activo pero es cuenta contraria: se mueve al crédito y resta del valor del equipo. Nunca se toca la cuenta Equipo directamente, así conservas el costo original y el desgaste por separado.', '{"lineas":[{"cuenta":"Gasto de Depreciación","padre":"Gasto","lado":"Débito","monto":100000},{"cuenta":"Depreciación Acumulada","padre":"Activo","lado":"Crédito","monto":100000}]}'::jsonb)
) as v(codigo, orden, tipo, nivel, enunciado, aviso, nota, datos);
