-- Semilla de «NVIDIA · Hugging Face»: startups y M&A avanzado.
--
-- Segunda clase del modelo. No comparte una línea de código con la
-- primera: mismas seis formas de diagrama, mismo motor de quiz, otro
-- contenido. Sus preguntas son de tipo `opcion`, así que no necesita
-- filas en `cuentas`.
--
-- Los hechos verificables (precio reportado, Serie D, Mellanox, Arm,
-- múltiplos) van con su fuente y su fecha. Las cifras que sirven de
-- ejemplo —la asignación del precio de compra, el earnout— van
-- rotuladas como supuesto de clase dentro del propio enunciado.

insert into public.clases (slug, nombre, etiqueta, titular, bajada, orden) values (
  'nvidia-hugging-face',
  'NVIDIA · Hugging Face',
  'Startups y M&A avanzado',
  'Una compra de USD 12.900 millones, por dentro.',
  '12 láminas y 12 preguntas sobre la compra de Hugging Face por NVIDIA: valoración y múltiplos, comprador estratégico, estructura del pago, earnout y escrow, asignación del precio, goodwill y riesgo regulatorio.'
, 2);

with c as (select id from public.clases where slug = 'nvidia-hugging-face')
insert into public.laminas (clase_id, orden, etiqueta, titulo, cuerpo, visual, datos)
select c.id, v.* from c, (values
  (1, 'El hecho · agosto 2026', '[{"t":"NVIDIA compra "},{"t":"Hugging Face","acento":true}]'::jsonb, '[{"tipo":"p","texto":"El 26 y 27 de agosto de 2026, The Information y Business Insider reportaron que NVIDIA acordó comprar Hugging Face por USD 12.900 millones. Sería, con diferencia, la mayor adquisición de su historia."},{"tipo":"p","texto":"A la fecha de esos reportes no había acuerdo firmado. Esta clase trabaja el caso tal como está: una operación anunciada por la prensa, todavía sin cerrar. Eso no la vuelve menos útil — casi todo el análisis de M&A se hace justamente en ese estado."}]'::jsonb, 'balance', '{"columnas":[{"rotulo":"2023 · Serie D","filas":[{"cuenta":"Valoración","monto":"USD 4.500 M"},{"cuenta":"Ronda","monto":"USD 235 M"}],"total":"USD 4.500 M"},{"rotulo":"2026 · Compra","filas":[{"cuenta":"Precio reportado","monto":"USD 12.900 M"},{"cuenta":"Acuerdo firmado","monto":"—"}],"total":"USD 12.900 M"}],"signo":"×2,9","sello":"Tres años entre una cifra y la otra"}'::jsonb),
  (2, 'Qué se compra', '[{"t":"El "},{"t":"GitHub de la IA","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Hugging Face no fabrica chips ni vende nube. Es el repositorio donde la comunidad publica y descarga modelos abiertos, datasets y benchmarks: la plaza a la que van todos los que sí venden chips y nube."},{"tipo":"lista","items":["Los pesos de los modelos abiertos","Los datasets de entrenamiento y evaluación","Las librerías con las que se usan","La comunidad que lo mantiene vivo"]},{"tipo":"p","texto":"Su valor no está en un activo que se pueda tocar ni en un contrato que se pueda ceder. Está en quién pasa por ahí todos los días. Eso hace difícil ponerle precio — y es exactamente el problema de esta clase."}]'::jsonb, 'partido', '{"mitades":[{"rotulo":"Quien fabrica el cómputo"},{"rotulo":"Quien reparte los modelos"}],"reglas":true}'::jsonb),
  (3, 'Fundamento', '[{"t":"Un precio parte un "},{"t":"excedente","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Una compra solo ocurre si la empresa vale más para el comprador que para el vendedor. Esa diferencia es el excedente del trato, y el precio decide cómo se reparte."},{"tipo":"p","texto":"Por debajo de lo que el vendedor cree que vale, no vende. Por encima de lo que vale para el comprador, no compra. Todo lo que pasa en una negociación de M&A —diligencia, earnouts, garantías— es discutir dónde cae el precio dentro de esa franja."}]'::jsonb, 'bloqueT', '{"nombre":"Excedente del trato","lados":[{"rotulo":"Se queda el comprador"},{"rotulo":"Se queda el vendedor"}],"pie":"Precio"}'::jsonb),
  (4, 'Startup · financiación', '[{"t":"Ya era "},{"t":"socio","acento":true},{"t":", ahora sería dueño"}]'::jsonb, '[{"tipo":"p","texto":"En agosto de 2023 Hugging Face levantó una Serie D de USD 235 millones liderada por Salesforce Ventures, con GV (Alphabet), Amazon, NVIDIA, Intel, AMD, Qualcomm, IBM Ventures y Sound Ventures. La valoración quedó en USD 4.500 millones."},{"tipo":"p","texto":"Media industria del silicio en la misma tabla de capitalización, y ninguno con control. Esa ronda compró neutralidad: todos adentro, nadie mandando. Comprar la empresa entera es exactamente lo contrario, y ahí empieza el problema regulatorio de la lámina 11."}]'::jsonb, 'registro', '{"titulo":"Serie D · agosto 2023","filas":[{"texto":"Salesforce Ventures","monto":"lidera"},{"texto":"GV · Amazon · IBM Ventures","monto":"participa"},{"texto":"NVIDIA · Intel · AMD · Qualcomm","monto":"participa"},{"texto":"Sound Ventures","monto":"participa"}],"pie":{"rotulo":"Ronda","valor":"USD 235 M"}}'::jsonb),
  (5, 'Valoración', '[{"t":"Un múltiplo, "},{"t":"no un precio","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Un múltiplo dice cuántas veces el ingreso anual vale la empresa. Sirve para comparar: un precio suelto no dice nada, un múltiplo se puede poner al lado de otro."},{"tipo":"p","texto":"La Serie D de 2023 valoró a Hugging Face en más de 100 veces su ingreso anualizado. El precio reportado en 2026 equivale a unas 86 veces, sobre un ARR estimado en USD 150 millones."},{"tipo":"p","texto":"El precio casi se triplicó y el múltiplo bajó. No es una contradicción: creció el denominador. Cuando el ingreso crece más rápido que la valoración, la empresa se vuelve más cara en dólares y más barata en múltiplos."}]'::jsonb, 'balance', '{"columnas":[{"rotulo":"2023 · Serie D","filas":[{"cuenta":"Valoración","monto":"USD 4.500 M"},{"cuenta":"Múltiplo","monto":">100×"}],"total":">100×"},{"rotulo":"2026 · Compra","filas":[{"cuenta":"Precio","monto":"USD 12.900 M"},{"cuenta":"ARR estimado","monto":"USD 150 M"}],"total":"~86×"}],"signo":"≠","sello":"Sube el precio, baja el múltiplo"}'::jsonb),
  (6, 'M&A avanzado · estructura', '[{"t":"Cuánto se paga y "},{"t":"con qué","acento":true}]'::jsonb, '[{"tipo":"p","texto":"La estructura de esta operación no se divulgó. Vale la pena saber qué está en juego cuando se decide, porque el «cuánto» y el «con qué» son dos negociaciones distintas."},{"tipo":"fichas","leyenda":"lo vuelve","items":[{"texto":"Efectivo","ficha":"Cierto hoy","tono":"info"},{"texto":"Acciones","ficha":"Atado al comprador","tono":"ciruela"},{"texto":"Earnout","ficha":"Atado al resultado","tono":"neutro"}]},{"tipo":"p","texto":"Pagar con acciones diluye a los accionistas del comprador y traslada al vendedor el riesgo del precio de la acción. Pagar en efectivo cierra la cifra pero consume caja o deuda. Casi todas las operaciones grandes mezclan las tres."}]'::jsonb, 'tabla', '{"columnas":[{"rotulo":"Forma de pago"},{"rotulo":"Riesgo del vendedor","sentido":"arriba"},{"rotulo":"Costo del comprador","sentido":"abajo"}],"filas":[{"celdas":[{"texto":"Efectivo"},{"texto":"Ninguno","tono":"info"},{"texto":"Caja o deuda","tono":"ciruela"}]},{"celdas":[{"texto":"Acciones"},{"texto":"Precio de la acción","tono":"ciruela"},{"texto":"Dilución","tono":"ciruela"}]},{"celdas":[{"texto":"Earnout"},{"texto":"Resultados futuros","tono":"ciruela"},{"texto":"Solo si se cumple","tono":"info"}]}]}'::jsonb),
  (7, 'M&A avanzado · el precio a plazos', '[{"t":"Earnout y "},{"t":"escrow","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Un earnout deja una parte del precio condicionada a que la empresa comprada cumpla metas. Aparece cuando las dos partes no se ponen de acuerdo en cuánto vale: en vez de discutir la proyección, la apuestan."},{"tipo":"p","texto":"Un escrow retiene otra parte en garantía, doce o veinticuatro meses, por si lo que el vendedor declaró no era cierto: un pleito que no contó, una licencia mal cedida, un pasivo escondido."},{"tipo":"p","texto":"Son dos riesgos distintos con dos remedios distintos. El earnout cubre que el negocio no rinda; el escrow, que el vendedor haya mentido."}]'::jsonb, 'flujo', '{"nodos":[{"texto":"Firma"},{"texto":"Cierre"},{"texto":"Escrow"},{"texto":"Earnout"}]}'::jsonb),
  (8, 'M&A avanzado · contabilidad', '[{"t":"El precio no es "},{"t":"lo que se compra","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Al cerrar, el comprador tiene que repartir el precio pagado entre todo lo que adquirió, a valor razonable: la caja, la tecnología, la marca, los contratos. Eso es la asignación del precio de compra."},{"tipo":"p","texto":"Nunca cuadra. Lo identificable siempre vale menos que lo pagado, porque una parte del precio se paga por cosas que no se pueden separar y vender aparte. Ese sobrante tiene nombre, y es la lámina siguiente."},{"tipo":"p","texto":"Las cifras del ejemplo son un supuesto de clase; el precio es el reportado."}]'::jsonb, 'balance', '{"columnas":[{"rotulo":"Lo que se paga","filas":[{"cuenta":"Precio de compra","monto":"USD 12.900 M"}],"total":"USD 12.900 M"},{"rotulo":"Lo que se identifica","filas":[{"cuenta":"Activos netos","monto":"USD 3.100 M"},{"cuenta":"Sobrante","monto":"USD 9.800 M"}],"total":"USD 12.900 M"}],"signo":"=","sello":"Todo el precio tiene que quedar asignado"}'::jsonb),
  (9, 'M&A avanzado · contabilidad', '[{"t":"El sobrante se llama "},{"t":"goodwill","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Goodwill es el residuo: precio pagado menos valor razonable de los activos netos identificables. En el ejemplo, USD 9.800 millones."},{"tipo":"p","texto":"No es un truco contable. Es lo que se compró y no se puede separar: las sinergias esperadas y el equipo ya reunido y funcionando. Cosas reales que ninguna norma deja reconocer por su cuenta."},{"tipo":"p","texto":"No se amortiza. Se somete a prueba de deterioro, al menos una vez al año. Si la unidad comprada deja de valer lo que se pagó, la pérdida entra de golpe al resultado — y por eso el goodwill termina siendo la cuenta que lleva la nota de si la compra salió bien."}]'::jsonb, 'partido', '{"mitades":[{"rotulo":"Identificable"},{"rotulo":"Goodwill"}],"reglas":true}'::jsonb),
  (10, 'M&A avanzado · el activo se va a las 6', '[{"t":"Lo que compras "},{"t":"se puede ir","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Si buena parte del precio es el equipo y la comunidad, entonces el activo camina y puede renunciar. El cierre suele ser el peor momento: las acciones de los fundadores y del equipo se liquidan de golpe y desaparece la razón económica para quedarse."},{"tipo":"fichas","leyenda":"sirve para","items":[{"texto":"Vesting acelerado","ficha":"Liberar","tono":"ciruela"},{"texto":"Paquete de retención","ficha":"Retener","tono":"info"},{"texto":"Earnout al equipo","ficha":"Alinear","tono":"neutro"}]},{"tipo":"p","texto":"Por eso una parte del precio se vuelve a atar: nuevas acciones que se ganan con el tiempo, bonos condicionados a permanencia, metas compartidas. Comprar la empresa es la parte fácil."}]'::jsonb, 'tabla', '{"columnas":[{"rotulo":"Riesgo"},{"rotulo":"Cuándo aparece","sentido":"arriba"},{"rotulo":"Con qué se ataja","sentido":"abajo"}],"filas":[{"celdas":[{"texto":"Fuga del equipo"},{"texto":"Al cierre","tono":"ciruela"},{"texto":"Retención","tono":"info"}]},{"celdas":[{"texto":"Fuga de la comunidad"},{"texto":"Al anuncio","tono":"ciruela"},{"texto":"Compromisos públicos","tono":"info"}]},{"celdas":[{"texto":"Choque cultural"},{"texto":"Meses después","tono":"ciruela"},{"texto":"Autonomía pactada","tono":"info"}]}]}'::jsonb),
  (11, 'M&A avanzado · el regulador', '[{"t":"La sombra de "},{"t":"Arm","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Una operación de USD 12.900 millones se notifica obligatoriamente en Estados Unidos y hay que esperar el plazo de ley antes de cerrar. La Unión Europea y probablemente el Reino Unido la revisarían también. La revisión se estiraría hasta 2027."},{"tipo":"p","texto":"La pregunta del regulador no es el tamaño: es si el dueño de las GPUs, siendo dueño del hub, lo inclinaría hacia su propio hardware y en contra de AMD, Intel y los chips propios de los hyperscalers. La neutralidad que la Serie D compró es justo lo que estaría en juego."},{"tipo":"p","texto":"NVIDIA ya vivió esto. En 2022 abandonó la compra de Arm por USD 40.000 millones tras la oposición de los reguladores. Mellanox, en 2020, sí pasó."}]'::jsonb, 'tabla', '{"columnas":[{"rotulo":"Operación"},{"rotulo":"Precio","sentido":"arriba"},{"rotulo":"Desenlace","sentido":"abajo"}],"filas":[{"celdas":[{"texto":"Mellanox · 2020"},{"texto":"USD 6.900 M"},{"texto":"Cerrada","tono":"info"}]},{"celdas":[{"texto":"Arm · 2022"},{"texto":"USD 40.000 M"},{"texto":"Abandonada","tono":"ciruela"}]},{"celdas":[{"texto":"Hugging Face · 2026"},{"texto":"USD 12.900 M"},{"texto":"Reportada","tono":"neutro"}]}]}'::jsonb),
  (12, 'Cómo leer una operación', '[{"t":"Reportado no es "},{"t":"cerrado","acento":true}]'::jsonb, '[{"tipo":"p","texto":"Entre que la prensa lo cuenta y que el dinero cambia de manos hay cuatro estados, y en cualquiera de ellos la operación se puede caer. Arm llegó a estar firmada y aun así no cerró."},{"tipo":"p","texto":"Lo primero al analizar cualquier compra es ubicarla en esa fila. Cambia todo: qué obliga a quién, quién paga si alguien se retira, y cuánto de lo que se lee es un hecho y cuánto es una intención."},{"tipo":"p","texto":"Al cierre de esta clase, la compra de Hugging Face está en el primer casillero."}]'::jsonb, 'flujo', '{"nodos":[{"texto":"Reportado"},{"texto":"Firmado"},{"texto":"Aprobado"},{"texto":"Cerrado"}]}'::jsonb)
) as v(orden, etiqueta, titulo, cuerpo, visual, datos);

with c as (select id from public.clases where slug = 'nvidia-hugging-face')
insert into public.preguntas (clase_id, codigo, orden, tipo, nivel, enunciado, aviso, nota, datos)
select c.id, v.* from c, (values
  ('01', 1, 'opcion', 'Básico', 'Según lo reportado por The Information y Business Insider a finales de agosto de 2026, ¿cuánto acordó pagar NVIDIA por Hugging Face?', null::text, 'USD 12.900 millones. Las otras tres cifras también son de esta historia: 4.500 fue la valoración de la Serie D de 2023, 6.900 lo que NVIDIA pagó por Mellanox en 2020 y 40.000 lo que ofreció por Arm antes de abandonar la operación en 2022.', '{"opciones":[{"texto":"USD 4.500 millones","correcta":false},{"texto":"USD 6.900 millones","correcta":false},{"texto":"USD 12.900 millones","correcta":true},{"texto":"USD 40.000 millones","correcta":false}]}'::jsonb),
  ('02', 2, 'opcion', 'Básico', '¿Qué hace de esta la mayor adquisición en la historia de NVIDIA?', null::text, 'Mellanox (2020, USD 6.900 millones) era la mayor compra que NVIDIA llegó a cerrar. La oferta por Arm era mucho más grande —USD 40.000 millones— pero se abandonó en 2022, y una operación que no cierra no cuenta como adquisición. La forma de pago no se ha divulgado.', '{"opciones":[{"texto":"Que supera los USD 6.900 millones de Mellanox, la mayor que había llegado a cerrar","correcta":true},{"texto":"Que es la primera vez que NVIDIA compra una empresa de software","correcta":false},{"texto":"Que supera los USD 40.000 millones que ofreció por Arm","correcta":false},{"texto":"Que se paga íntegramente en acciones","correcta":false}]}'::jsonb),
  ('03', 3, 'opcion', 'Básico', 'NVIDIA no llegaba a Hugging Face como un desconocido. ¿Cuál era la relación previa?', null::text, 'En agosto de 2023 Hugging Face levantó USD 235 millones liderados por Salesforce Ventures, con GV, Amazon, NVIDIA, Intel, AMD, Qualcomm, IBM Ventures y Sound Ventures. Pasar de coinversor minoritario —al lado de los competidores directos de NVIDIA— a dueño único es justamente lo que cambia el problema regulatorio.', '{"opciones":[{"texto":"Ya era accionista: participó en la Serie D de USD 235 millones de 2023","correcta":true},{"texto":"Hugging Face era una filial de NVIDIA desde su fundación","correcta":false},{"texto":"NVIDIA era su único proveedor de nube","correcta":false},{"texto":"No había ninguna relación previa","correcta":false}]}'::jsonb),
  ('04', 4, 'opcion', 'Básico', 'La Serie D de 2023 valoró a Hugging Face en USD 4.500 millones. Frente a esa cifra, el precio reportado de USD 12.900 millones representa aproximadamente:', null::text, '12.900 ÷ 4.500 ≈ 2,9. Ese cociente entre dos eventos de precio es el step-up, y es lo primero que mira un inversionista de la ronda anterior para saber cuánto rindió su plata.', '{"opciones":[{"texto":"Un aumento de 2,9 veces en tres años","correcta":true},{"texto":"Un aumento de 12,9 veces","correcta":false},{"texto":"Una rebaja del 65%","correcta":false},{"texto":"El mismo valor, ajustado por inflación","correcta":false}]}'::jsonb),
  ('05', 5, 'opcion', 'Intermedio', 'NVIDIA es un comprador estratégico, no financiero. ¿Qué implica eso para el precio que puede pagar?', null::text, 'Un fondo compra por el retorno del activo aislado, y su techo es lo que ese activo rinda por sí solo. Un estratégico suma las sinergias —lo que cambia en SU negocio— y por eso su techo es más alto. Esa diferencia es la razón por la que un vendedor busca compradores estratégicos.', '{"opciones":[{"texto":"Puede pagar más que un fondo, porque el valor no sale solo de Hugging Face sino de lo que hace con el negocio de NVIDIA","correcta":true},{"texto":"Paga menos, porque no necesita financiamiento externo","correcta":false},{"texto":"Paga exactamente el valor presente de los flujos de Hugging Face","correcta":false},{"texto":"El precio se lo fija el regulador","correcta":false}]}'::jsonb),
  ('06', 6, 'opcion', 'Intermedio', 'La estructura de pago no se divulgó. Si NVIDIA pagara con acciones propias en lugar de efectivo, ¿qué sería cierto?', null::text, 'Pagar con acciones emite propiedad nueva: cada accionista existente pasa a tener una tajada menor de la misma empresa. Y el vendedor deja de tener una cifra cierta — lo que reciba depende de dónde esté la acción al cierre y de cuánto tiempo esté obligado a conservarla.', '{"opciones":[{"texto":"Los accionistas de NVIDIA se diluyen y el vendedor queda expuesto al precio de la acción","correcta":true},{"texto":"No hay dilución, porque las acciones ya existen","correcta":false},{"texto":"El vendedor recibe el mismo valor con menos riesgo que en efectivo","correcta":false},{"texto":"La operación deja de necesitar aprobación regulatoria","correcta":false}]}'::jsonb),
  ('07', 7, 'opcion', 'Intermedio', 'Supón que del precio se dejan USD 1.500 millones condicionados a que Hugging Face alcance ciertas metas en 2028. ¿Cómo se llama eso y qué resuelve?', null::text, 'Un earnout parte el precio en dos: lo cierto hoy y lo condicionado a resultados futuros. Aparece cuando comprador y vendedor no se ponen de acuerdo en cuánto vale la empresa — en vez de discutir la proyección, la apuestan. Escrow, break fee y vesting resuelven otros tres problemas distintos.', '{"opciones":[{"texto":"Escrow: garantiza que las declaraciones del vendedor sean ciertas","correcta":false},{"texto":"Earnout: traslada al vendedor el riesgo de que el negocio no rinda lo prometido","correcta":true},{"texto":"Break fee: compensa al vendedor si el comprador se retira","correcta":false},{"texto":"Vesting: retiene al equipo fundador","correcta":false}]}'::jsonb),
  ('08', 8, 'opcion', 'Intermedio', 'En una operación de este tamaño se suele retener parte del precio en garantía (escrow) durante 12 a 24 meses. ¿Contra qué protege?', null::text, 'El escrow cubre lo que el vendedor afirmó y no era cierto. El riesgo de mercado se cubre con el earnout, el regulatorio con las condiciones de cierre y el break fee, y la fuga del equipo con retención y vesting. Cuatro riesgos, cuatro instrumentos.', '{"opciones":[{"texto":"Contra que el mercado de la IA se enfríe","correcta":false},{"texto":"Contra que los reguladores bloqueen la operación","correcta":false},{"texto":"Contra que las declaraciones y garantías del vendedor resulten falsas: un pleito oculto, una licencia mal cedida, un pasivo no declarado","correcta":true},{"texto":"Contra que los fundadores se vayan","correcta":false}]}'::jsonb),
  ('09', 9, 'opcion', 'Avanzado', 'Supón que, al asignar el precio de compra, los activos netos identificables de Hugging Face se valoran en USD 3.100 millones. Con un precio de USD 12.900 millones, ¿cuánto goodwill se reconoce?', 'Las cifras de la asignación son un supuesto de clase; el precio es el reportado.', '12.900 − 3.100 = 9.800. El goodwill es el residuo de la asignación: lo pagado por encima del valor razonable de lo identificable. Nunca se calcula directamente, siempre sale por diferencia.', '{"opciones":[{"texto":"USD 3.100 millones","correcta":false},{"texto":"USD 9.800 millones","correcta":true},{"texto":"USD 12.900 millones","correcta":false},{"texto":"Cero: el goodwill solo aparece cuando se paga por debajo del valor en libros","correcta":false}]}'::jsonb),
  ('10', 10, 'opcion', 'Avanzado', '¿Qué representa ese goodwill y qué pasa con él en los años siguientes?', null::text, 'Ni bajo NIIF ni bajo US GAAP se amortiza: se prueba por deterioro al menos una vez al año. Si la unidad comprada deja de valer lo que se pagó, la pérdida entra de golpe al resultado. Eso convierte al goodwill en la cuenta que lleva la nota de si la compra salió bien.', '{"opciones":[{"texto":"El exceso pagado sobre lo identificable —sinergias esperadas y el equipo ya reunido, que no se pueden reconocer por separado—; no se amortiza, se prueba por deterioro","correcta":true},{"texto":"Una cuenta de orden que no entra al balance","correcta":false},{"texto":"Un activo que se amortiza en línea recta a cinco años","correcta":false},{"texto":"La diferencia entre el precio y la capitalización bursátil del comprador","correcta":false}]}'::jsonb),
  ('11', 11, 'opcion', 'Avanzado', 'En 2022 NVIDIA abandonó la compra de Arm (USD 40.000 millones) tras la oposición de los reguladores. ¿Qué riesgo concreto ilustra ese precedente aquí?', null::text, 'Una operación de USD 12.900 millones obliga a notificar en Estados Unidos y a esperar el plazo de ley; la Unión Europea y probablemente el Reino Unido también la revisarían, mirando si el hub dejaría de ser neutral frente a AMD, Intel y los chips propios de los hyperscalers. Mellanox pasó y Arm no: lo que cambia es el tamaño y la centralidad del activo.', '{"opciones":[{"texto":"Riesgo de que el precio suba durante la revisión","correcta":false},{"texto":"Riesgo cambiario, porque la revisión toma meses","correcta":false},{"texto":"Ninguno: Mellanox se aprobó, así que esta también","correcta":false},{"texto":"Riesgo de cierre: una operación así se notifica y se revisa, y la duda es si NVIDIA inclinaría un hub neutral hacia su propio hardware","correcta":true}]}'::jsonb),
  ('12', 12, 'opcion', 'Avanzado', 'A la fecha de los reportes no había acuerdo firmado. ¿Qué implica eso para la operación?', null::text, 'Reportado es prensa. Firmado es un contrato con condiciones de cierre. Aprobado es el regulador. Cerrado es cuando cambian el dinero y las acciones. Arm llegó a estar firmada y aun así no cerró. Lo primero al analizar una operación es saber en cuál de los cuatro estados está.', '{"opciones":[{"texto":"Que ya es vinculante y solo falta el papeleo","correcta":false},{"texto":"Que el precio ya no puede cambiar","correcta":false},{"texto":"Que los reguladores ya la aprobaron","correcta":false},{"texto":"Que todavía nada obliga a las partes: entre reportado, firmado, aprobado y cerrado hay cuatro estados, y en cualquiera se puede caer","correcta":true}]}'::jsonb)
) as v(codigo, orden, tipo, nivel, enunciado, aviso, nota, datos);
