-- Las preguntas de «NVIDIA · Hugging Face», rehechas.
--
-- La primera versión preguntaba cifras: cuánto se pagó, cuánto valía
-- antes, cuántas veces más. Eso se responde recordando, no entendiendo, y
-- no es lo que la clase enseña.
--
-- Estas preguntan el concepto y usan la operación como el caso donde el
-- concepto se ve: qué es una valoración, por qué una empresa vale más de
-- lo que factura, qué mide un múltiplo, qué diluye y qué no, qué compra un
-- estratégico que un fondo no puede comprar, qué riesgo cubre cada
-- instrumento del contrato, de dónde sale el goodwill y qué teme el
-- regulador. Las cifras siguen ahí, pero dentro del enunciado y como dato
-- de trabajo: ninguna pregunta se responde recordando un número.
--
-- Se reemplazan enteras y no se editan en sitio porque cambia lo que
-- preguntan, no cómo lo preguntan. La clase no tiene respuestas enviadas,
-- así que no se pierde el trabajo de nadie; el guard lo comprueba.

do $$
begin
  if exists (
    select 1 from public.respuestas r
      join public.preguntas q on q.id = r.pregunta_id
      join public.clases c on c.id = q.clase_id
     where c.slug = 'nvidia-hugging-face'
  ) then
    raise exception 'Hay respuestas enviadas en esta clase: reemplazar las preguntas las borraría.';
  end if;
end $$;

delete from public.preguntas q
 using public.clases c where c.id = q.clase_id and c.slug = 'nvidia-hugging-face';

with c as (select id from public.clases where slug = 'nvidia-hugging-face')
insert into public.preguntas (clase_id, codigo, orden, tipo, nivel, enunciado, aviso, nota, datos)
select c.id, v.* from c, (values
  ('01', 1, 'opcion', 'Básico', 'La Serie D de 2023 valoró a Hugging Face en USD 4.500 millones, y en esa ronda la empresa levantó USD 235 millones. ¿Qué es exactamente esa valoración?', null::text, 'Una valoración es un precio implícito, no un saldo. Nadie puso 4.500 sobre la mesa: unos inversionistas pusieron 235 por un porcentaje, y de esa proporción sale la cifra de la empresa entera. Por eso una valoración no dice cuánta caja tiene la empresa, ni cuánto factura, ni cuánto va a pagar el próximo comprador — como se ve tres años después, cuando la cifra ya es otra.', '{"opciones":[{"texto":"El dinero que quedó en la caja de Hugging Face después de la ronda.","correcta":false},{"texto":"El precio implícito de la empresa entera, extrapolado de lo que unos inversionistas pagaron por una parte pequeña de ella.","correcta":true},{"texto":"La suma de todo lo que Hugging Face ha facturado desde que se fundó.","correcta":false},{"texto":"El precio mínimo que cualquier comprador está obligado a pagar por ella.","correcta":false}]}'::jsonb),
  ('02', 2, 'opcion', 'Básico', 'Hugging Face aloja modelos y datasets abiertos, y para la mayoría de quienes lo usan es gratis. ¿Por qué una empresa así puede valer miles de millones?', null::text, 'Lo que un comprador paga no es la facturación de hoy sino el control de un punto de paso. El balance no registra nada de eso —ni la comunidad, ni el hábito, ni el efecto de red—, y por eso una empresa puede valer un múltiplo enorme de lo que factura. Ese hueco entre lo que se paga y lo que la contabilidad sabe reconocer reaparece más adelante con otro nombre: goodwill.', '{"opciones":[{"texto":"Porque el valor de una empresa es la suma de los activos que tiene registrados en su balance.","correcta":false},{"texto":"Porque los modelos que aloja pasan a ser de su propiedad y puede venderlos.","correcta":false},{"texto":"Porque lo que se compra es la posición que ocupa: el sitio por donde pasan los desarrolladores que deciden sobre qué hardware corre la IA.","correcta":true},{"texto":"Porque los repositorios de software se deprecian y generan un escudo fiscal.","correcta":false}]}'::jsonb),
  ('03', 3, 'opcion', 'Básico', 'Entre 2023 y 2026 el precio de Hugging Face casi se triplicó y, sin embargo, su múltiplo sobre ingresos bajó: de más de 100 veces a unas 86. ¿Cómo pueden pasar las dos cosas a la vez?', null::text, 'Un múltiplo es una división: precio sobre ingreso. Si el denominador crece más rápido que el numerador, el cociente baja aunque el numerador suba. Por eso un múltiplo sirve para comparar una empresa con otra y no para decir, por sí solo, si está cara: uno alto suele significar que el mercado espera crecimiento, y uno bajo, que el crecimiento ya llegó.', '{"opciones":[{"texto":"Porque el ingreso creció más rápido que el precio: la empresa se volvió más cara en dólares y más barata en múltiplos.","correcta":true},{"texto":"Porque el múltiplo y el precio miden lo mismo, así que una de las dos cifras tiene que estar mal.","correcta":false},{"texto":"Porque los múltiplos bajan solos con el paso del tiempo, como una amortización.","correcta":false},{"texto":"Porque al bajar el múltiplo la empresa perdió valor, aunque le hayan pagado más.","correcta":false}]}'::jsonb),
  ('04', 4, 'opcion', 'Básico', 'En esa ronda entraron a la vez Salesforce Ventures, GV, Amazon, NVIDIA, Intel, AMD, Qualcomm e IBM Ventures —varios de ellos competidores entre sí— y ninguno quedó con control. ¿Qué gana una startup repartiendo así su ronda en vez de concentrarla en un solo socio?', null::text, 'La dilución no depende de cuántos inversionistas entren sino de cuánto dinero se levanta y a qué precio: repartir la misma ronda entre ocho socios diluye exactamente igual que dársela a uno. Lo que cambia es el poder. Con media industria del silicio adentro y nadie mandando, el repositorio podía seguir siendo neutral — que es justamente lo que un dueño único pone en duda.', '{"opciones":[{"texto":"Se diluye menos, porque repartir la ronda entre muchos obliga a emitir menos acciones.","correcta":false},{"texto":"Evita tener que registrar la ronda en su tabla de capitalización.","correcta":false},{"texto":"Se asegura de que todos ellos tengan que aprobar cualquier venta futura.","correcta":false},{"texto":"Conserva su neutralidad: ningún socio puede inclinar el producto hacia sí mismo ni vetar una decisión.","correcta":true}]}'::jsonb),
  ('05', 5, 'opcion', 'Intermedio', 'NVIDIA vende GPUs; Hugging Face reparte modelos. ¿Por qué esa combinación le permite a NVIDIA pagar más de lo que pagaría un fondo de inversión por la misma empresa?', null::text, 'Eso es una sinergia, y es lo que separa a un comprador estratégico de uno financiero. El fondo compra por lo que el activo rinde por su cuenta, y ahí tiene un techo. El estratégico suma lo que cambia en su propio negocio, y su techo es más alto. Por eso un vendedor que quiere maximizar el precio busca estratégicos — y por eso el regulador los mira con más cuidado.', '{"opciones":[{"texto":"Porque los compradores estratégicos consiguen deuda más barata que los fondos.","correcta":false},{"texto":"Porque un fondo está obligado a pagar el valor en libros y un comprador estratégico no.","correcta":false},{"texto":"Porque parte de lo que NVIDIA compra no está dentro de Hugging Face, sino en lo que Hugging Face le hace a su propio negocio.","correcta":true},{"texto":"Porque NVIDIA no tiene que pasar por revisión regulatoria y un fondo sí.","correcta":false}]}'::jsonb),
  ('06', 6, 'opcion', 'Intermedio', 'La estructura del pago no se divulgó. Si NVIDIA cubriera una parte con acciones propias en vez de efectivo, ¿qué cambiaría para cada lado?', null::text, 'Pagar con acciones mueve riesgo en las dos direcciones: el vendedor queda expuesto al precio de una empresa que no controla, y a veces obligado a conservar los títulos un tiempo; el comprador emite propiedad nueva y reparte la suya entre más manos. Pagar en efectivo cierra la cifra, pero consume caja o deuda. Ninguna sale gratis, y por eso las operaciones grandes casi siempre mezclan las dos.', '{"opciones":[{"texto":"Nada de fondo: el día del cierre las acciones y el efectivo valen lo mismo.","correcta":false},{"texto":"El vendedor asumiría menos riesgo, porque una acción de NVIDIA es más segura que el efectivo.","correcta":false},{"texto":"NVIDIA evitaría diluirse, porque entregaría acciones que ya estaban emitidas.","correcta":false},{"texto":"El vendedor dejaría de tener una cifra cierta —depende de dónde esté la acción— y los accionistas de NVIDIA se quedarían con una tajada menor de su empresa.","correcta":true}]}'::jsonb),
  ('07', 7, 'opcion', 'Intermedio', 'Comprador y vendedor coinciden en casi todo menos en cuánto va a crecer el negocio en los próximos tres años: el vendedor proyecta el doble que el comprador. ¿Qué instrumento cierra el trato sin que ninguno tenga que aceptar la proyección del otro?', null::text, 'El earnout convierte un desacuerdo en una apuesta: en vez de discutir de quién es la proyección correcta, se paga según cuál se cumpla. Cuesta caro en otra moneda —hay que definir la métrica, medirla durante años y aguantar la tentación de manipularla en ambos sentidos—, pero desatasca operaciones que si no, no se firman. Escrow, break fee y no competencia resuelven otros tres problemas; ninguno es este.', '{"opciones":[{"texto":"Un earnout: se condiciona una parte del precio a que se cumplan las metas, y cada uno cobra según lo que resulte cierto.","correcta":true},{"texto":"Un escrow: se retiene una parte del precio hasta verificar lo que el vendedor declaró.","correcta":false},{"texto":"Un break fee: se pacta una multa para la parte que se retire.","correcta":false},{"texto":"Una cláusula de no competencia sobre los fundadores.","correcta":false}]}'::jsonb),
  ('08', 8, 'opcion', 'Intermedio', 'Hugging Face aloja modelos y datasets subidos por terceros. Si un año después del cierre aparece un pleito por algo que se subió antes, ¿qué parte del contrato está pensada para que ese costo no lo termine pagando el comprador?', null::text, 'El vendedor afirma por escrito un montón de cosas —que no hay pleitos ocultos, que las licencias están en regla, que no hay pasivos sin declarar—: eso son las declaraciones y garantías. Si alguna resulta falsa, el escrow es el dinero ya apartado para cubrirlo, y por eso se libera meses o años después del cierre. Es un riesgo distinto del que cubre un earnout: aquí no se trata de que el negocio no rinda, sino de que lo que dijeron no era cierto.', '{"opciones":[{"texto":"El earnout, porque un pleito reduciría los resultados futuros.","correcta":false},{"texto":"Las declaraciones y garantías del vendedor, respaldadas por una retención en garantía —escrow— durante uno o dos años.","correcta":true},{"texto":"El break fee, porque un pleito es motivo suficiente para retirarse.","correcta":false},{"texto":"Ninguna: al cerrar, todo el riesgo pasa al comprador sin excepción.","correcta":false}]}'::jsonb),
  ('09', 9, 'opcion', 'Avanzado', 'Si buena parte de lo que se paga es el equipo y la comunidad, el cierre es el momento de más riesgo: las acciones de los fundadores y del equipo se liquidan de golpe. ¿Por qué eso es un problema para el comprador y cómo se ataja?', null::text, 'Es el problema de fondo de comprar una empresa cuyo valor camina y puede renunciar. Al cerrar, el vesting suele acelerarse y todo el mundo cobra: justo cuando más falta hace que se queden. Por eso el comprador reata una parte del precio al futuro —vesting nuevo, paquetes de retención, a veces un earnout dirigido al equipo—. En un repositorio abierto el riesgo se duplica: además del equipo se puede ir la comunidad, que no firmó nada.', '{"opciones":[{"texto":"No es un problema: al cerrar, los contratos laborales pasan al comprador y obligan al equipo a quedarse.","correcta":false},{"texto":"Es un problema contable, y se ataja registrando al equipo como un intangible amortizable.","correcta":false},{"texto":"Desaparece la razón económica para quedarse, así que una parte del precio se vuelve a atar: acciones nuevas que se ganan con el tiempo y bonos condicionados a permanencia.","correcta":true},{"texto":"Se ataja con una cláusula de exclusividad que impide al vendedor negociar con otros compradores.","correcta":false}]}'::jsonb),
  ('10', 10, 'opcion', 'Avanzado', 'Al cerrar, el comprador tiene que repartir el precio pagado entre todo lo que adquirió, a valor razonable. En una empresa cuyo valor está en la comunidad y en el equipo reunido, ¿dónde termina la mayor parte del precio y qué pasa con eso después?', null::text, 'El goodwill no se calcula, sobra: es el precio menos el valor razonable de lo identificable. Recoge exactamente lo que ninguna norma deja reconocer por separado —las sinergias esperadas y el equipo ya armado y funcionando—. Y como no se amortiza sino que se prueba por deterioro, termina siendo la cuenta que lleva la nota de si la compra salió bien: mientras nadie la toque la tesis sigue en pie; el día que se deteriora, el mercado se entera de golpe.', '{"opciones":[{"texto":"En goodwill, que sobra por diferencia y no se amortiza: se prueba por deterioro, y si la unidad deja de valer lo pagado la pérdida entra de golpe al resultado.","correcta":true},{"texto":"En un intangible identificable, que se amortiza en línea recta a cinco años.","correcta":false},{"texto":"En el gasto del período: lo que no se puede tocar no entra al balance.","correcta":false},{"texto":"Repartido en proporción entre los activos fijos que ya existían.","correcta":false}]}'::jsonb),
  ('11', 11, 'opcion', 'Avanzado', 'Un regulador no bloquea una compra por ser grande, sino por lo que puede cambiar en el mercado. En esta operación, ¿cuál es la preocupación concreta?', null::text, 'Comprador y comprado no compiten entre sí: están en capas distintas de la misma cadena. Ahí el daño que se teme no es que desaparezca un competidor, sino que el dueño de una capa use ese control para estorbar a los competidores de la otra. Es la razón por la que Mellanox (2020) pasó y Arm (2022) no: lo que cambia no es el tamaño, sino qué tan central es el activo para los rivales del comprador.', '{"opciones":[{"texto":"Que NVIDIA suba el precio de las suscripciones de pago de Hugging Face.","correcta":false},{"texto":"Que la operación reduzca el número de empresas que publican modelos abiertos.","correcta":false},{"texto":"Que NVIDIA concentre demasiados ingenieros de IA en un solo país.","correcta":false},{"texto":"Que el dueño del hardware, siendo dueño del repositorio neutral, lo incline hacia sus propias GPUs y en contra de AMD, Intel y los chips propios de los hyperscalers.","correcta":true}]}'::jsonb),
  ('12', 12, 'opcion', 'Avanzado', 'A la fecha de los reportes no había acuerdo firmado, y una revisión regulatoria de este tamaño se estira más de un año. ¿Qué implica eso para quien analiza la operación hoy?', null::text, 'Reportado es prensa: no obliga a nadie. Firmado es un contrato, con condiciones de cierre y normalmente un break fee para quien se retire. Aprobado es el regulador. Cerrado es cuando cambian de manos el dinero y las acciones. NVIDIA recorrió tres de esos casilleros con Arm y aun así no llegó al cuarto. Lo primero que hay que preguntar de cualquier operación es en cuál está.', '{"opciones":[{"texto":"Que el precio ya quedó fijado y solo falta el trámite.","correcta":false},{"texto":"Que si la prensa lo reportó, las partes ya quedaron obligadas entre sí.","correcta":false},{"texto":"Que el retraso favorece al vendedor, que cobra intereses mientras espera.","correcta":false},{"texto":"Que entre reportado, firmado, aprobado y cerrado hay cuatro estados distintos, y en cualquiera de ellos se puede caer.","correcta":true}]}'::jsonb)
) as v(codigo, orden, tipo, nivel, enunciado, aviso, nota, datos);

-- Dos láminas ganan el párrafo que sostiene las preguntas nuevas: la
-- diferencia entre lo levantado y la valoración, y la que separa a un
-- comprador estratégico de uno financiero.
update public.laminas l set cuerpo = jsonb_insert(l.cuerpo, '{1}', '{"tipo":"p","texto":"Ojo con las dos cifras: 235 es el dinero que entró a la caja; 4.500 es el precio implícito de la empresa entera, extrapolado del porcentaje que esos 235 compraron. Una valoración es un precio, no un saldo."}'::jsonb)
  from public.clases c
 where c.id = l.clase_id and c.slug = 'nvidia-hugging-face' and l.orden = 4;

update public.laminas l set cuerpo = l.cuerpo || jsonb_build_array('{"tipo":"p","texto":"De ahí sale la diferencia entre un comprador financiero y uno estratégico. El fondo solo puede contar lo que la empresa rinde por su cuenta, así que su techo es bajo. El estratégico suma lo que la empresa le hace a su propio negocio —eso es una sinergia— y por eso puede pagar más por exactamente lo mismo."}'::jsonb)
  from public.clases c
 where c.id = l.clase_id and c.slug = 'nvidia-hugging-face' and l.orden = 3;
